name: aly_oss
description: An aliyun oss plugin for flutter. Use this plugin to upload files to aliyun oss.
version: 1.0.1
homepage: https://github.com/flmn/aly_oss

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: tech.jitao.aly_oss
    pluginClass: AlyOssPlugin
